name: huawei_hmsavailability_example
description: Demonstrates how to use the Huawei Hmsavailability Plugin.

publish_to: none

environment:
  sdk: ">=3.5.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  huawei_hmsavailability:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  

flutter:
  uses-material-design: true
