name: hms_flutter_plugin

packages:
  - "./**"
  # - "./**/example"

command:
  bootstrap:
    environment:
      sdk: ">=3.5.3 <4.0.0"
      flutter: ">=3.24.0 <4.0.0"

scripts:
  fix:
    run: melos exec -c 1 -- "dart format . && dart fix --apply"
    description: Run dart format && dart fix"
  
  upgrade:
    run: melos exec -c 1 -- "dart pub upgrade --major-versions"
    description: Run dart pub upgrade --major-versions
