name: huawei_health_example
description: Demonstrates how to use the HUAWEI Health Kit Plugin.

publish_to: none

environment:
  sdk: ">=3.5.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  huawei_health:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
