name: huawei_modeling3d_example
description: Demonstrates how to use the huawei_modeling3d plugin.

publish_to: none

environment:
  sdk: ">=3.5.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  huawei_modeling3d:
    path: ../
  path_provider: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/material_generation_images/
    - assets/3D_reconstruction_images/
