name: huawei_ml_text_example
description: Demonstrates how to use the Huawei ML Text Plugin.

publish_to: none

environment:
  sdk: ">=3.5.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  huawei_ml_text:
    path: ../
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/bcr.png
    - assets/doc.png
    - assets/gcr.png
    - assets/text.png
    - assets/user.png
    - assets/icr.png
    - assets/textembed.png
    - assets/textlens.png
