name: huawei_ar_example
description: Demonstrates how to use the Huawei AR Engine Flutter Plugin.

publish_to: none

environment:
  sdk: ">=3.5.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  huawei_ar:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/blub.obj
    - assets/blub_texture.png
    - assets/bob.obj
    - assets/bob_texture.png
    - assets/blue_texture.png
    - assets/image_default.png
    - assets/mode_id.json
