name: huawei_contactshield_example
description: Demonstrates how to use the Huawei Contact Shield plugin.

publish_to: none

environment:
  sdk: ">=3.5.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  huawei_contactshield:
    path: ../
  file_picker: ^8.1.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
